version: '3'

services:
  proxy:
    build:
      context: .
      dockerfile: ./docker/proxy/Dockerfile
    volumes:
      - ./data/ssl:/usr/local/apache2/ssl
    ports:
      - "80:80"
      - "443:443"

  db:
   image: postgres
   # mounts db files to local machine filesystem
   volumes:
      - ./data/mount/postgres-data:/var/lib/postgresql/data
   environment:
     POSTGRES_USER: "vm_db_user"
     POSTGRES_PASSWORD: "vm_password"
     POSTGRES_DB: "vm_database"

  django:
    build: 
      context: .
      dockerfile: ./docker/django/Dockerfile
    # mounts user information files to local machine filesystem
    volumes:
      - ./data/mount/private:/opt/vm-django/system/private
      - ./data/mount/vm-static:/opt/vm-django/static
    command: ./wait-for-it.sh db:5432 -- ./start.sh
    expose:
      - "80"
    depends_on:
      - "db"
      - "proxy"
    links:
      - "db"
      - "proxy"

  angular:
    build:
      context: .
      dockerfile: ./docker/angular/Dockerfile
    expose:
      - "80"
    depends_on:
      - "proxy"
      - "django"
    links:
      - "proxy"
      - "django" 
