version: '3'

services:
  proxy:
    build:
      context: .
      dockerfile: ./docker/proxy/Dockerfile
    volumes:
      - ./data/ssl:/usr/local/apache2/ssl
    ports:
      - "80:80"
      - "443:443"

  db:
   image: postgres
   # mounts db files to local machine filesystem
   volumes:
      - ./data/mount/postgres-data:/var/lib/postgresql/data
   environment:
     POSTGRES_USER: "${POSTGRES_USER}"
     POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
     POSTGRES_DB: "${POSTGRES_DB}"
     SUPER_USER: "${SUPER_USER}"
     SUPER_PASS: "${SUPER_PASS}"
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    # mounts user information files to local machine filesystem
    volumes:
      - ./data/mount/private:/opt/vm-django/system/private
      - ./data/mount/vm-static:/opt/vm-django/static
    command: ./wait-for-it.sh db:5432 -- ./start.sh
    expose:
      - "80"
    depends_on:
      - "db"
      - "proxy"
    links:
      - "db"
      - "proxy"
    env_file:
        - .env

  angular:
    build:
      context: .
      dockerfile: ./docker/angular/Dockerfile
    expose:
      - "80"
    depends_on:
      - "proxy"
      - "django"
    links:
      - "proxy"
      - "django"
