version: '3'

services: 
  web:
    build: .
    command: python vm-django/manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/virtual-mystery
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
