version: '3'

services: 
  django:
    build: .
    command: python vm-django/manage.py makemigrations
    command: python vm-django/manage.py migrate
    command: python vm-django/manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/virtual-mystery
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - test_db:/var/lib/postgresql/data
  angular:
    container_name: angular-service
    build: ./vm-angular
    volumes: 
      - './vm-angular:/usr/src/app'
    ports:
      - "4200:4200"
      
volumes:
  test_db:



