version: '3'

services:

  nginx:
    image: nginx:latest
    container_name: vm-nginx
    ports:
      - "8000:8000"
    volumes:
      - ./vm-django/config/nginx:/etc/nginx/conf.d
    depends_on:
      - django
  # proxy:

  #   build:
  #     context: .
  #     dockerfile: ./docker/proxy/Dockerfile
  #   image: virtualmystery/vm-proxy:test
  #   volumes:
  #     #- ./data/ssl:/usr/local/apache2/ssl
  #   ports:
  #     - "80:80"
  #     - "443:443"


  django:
    build:
      context: .
      dockerfile: ./vm-django/Dockerfile
    # mounts user information files to local machine filesystem
    image: virtualmystery/vm-django:test
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn mydjango.wsgi -b 0.0.0.0:8000"
    # volumes:
    #   - ./data/mount/private:/opt/vm-django/system/private
    #   - ./data/mount/vm-static:/opt/vm-django/static
    # command: ./wait-for-it.sh db:5432 -- ./start.sh
    expose:
      - "8000"
    depends_on:
      - "db"
  db:
    image: postgres
    # mounts db files to local machine filesystem
    #volumes:
        #- ./data/mount/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"

  angular:
    build:
      context: .
      dockerfile: ./docker/angular/Dockerfile
    image: virtualmystery/vm-angular:test
    expose:
      - "8000"
    depends_on:
      - "nginx"
      - "django"